### ISSUE TITLE
armv7l 遇到 bim-core 出错

### ISSUE THREAD

**Issue by v-JiangNan** [i-abc/Speedtest#10]
------------------------ 多功能 自更新 测速脚本 ------------------------
 Version               : v2023-09-21
 Usage                 : bash <(curl -sL bash.icu/speedtest)
 GitHub                : https://github.com/i-abc/speedtest
------------------------------------------------------------------------
loc: CN
使用镜像源
正在检测所需的tar是否安装
/usr/bin/tar
正在检测所需的curl是否安装
/usr/bin/curl
正在检测所需的iperf3是否安装
/usr/bin/iperf3
正在检测所需的bc是否安装
/usr/bin/bc
https://jihulab.com/i-abc/speedtest/-/raw/asset/speedtest-cli/ookla-speedtest-1.2.0-linux-armhf.tgz
speedtest-cli下载中
######################################################################################################################################### 100.0%
https://jihulab.com/i-abc/speedtest/-/raw/asset/bim-core/bimc--unknown-linux-musl
bim-core下载中
######################################################################################################################################### 100.0%#=O#-  #     #
https://jihulab.com/i-abc/speedtest/-/raw/asset/speedtest-go/speedtest-go_1.6.5_Linux_armv7.tar.gz
speedtest-go下载中
######################################################################################################################################### 100.0%
https://jihulab.com/i-abc/speedtest/-/raw/asset/librespeed-cli/librespeed-cli_1.0.10_linux_armv7.tar.gz
librespeed-cli下载中
######################################################################################################################################### 100.0%
经检测，bim-core的SHA-256与官方不符，方便的话欢迎到GitHub反馈

**Comment by i-abc** [comment]
请问 CPU 具体是什么型号，或者主机是什么？
能方便跑一下下面这么命令吗？
```
uname -a; echo "-----"; lscpu
```

**Comment by i-abc** [comment]
我完善了一下，应该没问题了。

但由于 armv7l 架构的 CPU 缺少上游组件的支持，无法完成单线程测速（如下图红框所示），其他测试项可以照常使用。

![image](https://github.com/i-abc/Speedtest/assets/104631897/6e1644e4-bd15-4817-bff9-a0dc4ab58559)
