### ISSUE TITLE
speedtest-go的SHA-256与官方不符

### ISSUE THREAD

**Issue by ming199999** [i-abc/Speedtest#12]
CPU Model            : Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
 CPU Cores            : 2 Cores 2499.996 MHz x86_64
 CPU Cache            : 30720 KB 
 OS                   : CentOS 7.9.2009 (64 Bit) KVM
 Kernel               : 3.10.0-1160.88.1.el7.x86_64
以上是VPS架构和CPU
下面是错误记录

Complete!
/usr/bin/iperf3
正在检测所需的bc是否安装
/usr/bin/bc
https://jihulab.com/i-abc/speedtest/-/raw/asset/speedtest-cli/v1.2.0/ookla-speedtest-1.2.0-linux-x86_64.tgz
speedtest-cli下载中
######################################################################## 100.0%
https://jihulab.com/i-abc/speedtest/-/raw/asset/bim-core/v0.16.0/bimc-x86_64-unknown-linux-musl
bim-core下载中
######################################################################## 100.0%
https://jihulab.com/i-abc/speedtest/-/raw/asset/speedtest-go/v1.6.6/speedtest-go_1.6.6_Linux_x86_64.tar.gz
speedtest-go下载中

curl: (35) TCP connection reset by peer
https://jihulab.com/i-abc/speedtest/-/raw/asset/librespeed-cli/v1.0.10/librespeed-cli_1.0.10_linux_amd64.tar.gz
librespeed-cli下载中
######################################################################## 100.0%
sha256sum: ./sp-github-i-abc/speedtest-go.tar.gz: No such file or directory
经检测，speedtest-go的SHA-256与官方不符，方便的话欢迎到GitHub反馈

**Comment by i-abc** [comment]
可能是当时网络波动导致下载失败，你再试一试看情况如何。
