### ISSUE TITLE
希望可以命令行直接调用

### ISSUE THREAD

**Issue by YangHaoNing-CN** [i-abc/Speedtest#21]
我在写一个整体的脚本，希望这个您的脚本可以支持通过命令行加参数来调用，并且通过这种方式输出时只输出测试结果，不输出别的内容。

**Comment by i-abc** [comment]
我这个主要是交互式的，实现你这个目的改起来比较麻烦；你试试在你的脚本里直接用上游的那些测速工具，它们原本就是支持命令行加参数调用、只输出测试结果的，相对而言工作量会小一点。

**Comment by YangHaoNing-CN** [comment]
脚本逻辑我有点看不懂，默认的节点列表是保存在哪里的呢?

**Comment by i-abc** [comment]
保存在外部文件里的，你最好还是直接用上游的测速工具，我这个一坨屎山。

**Comment by YangHaoNing-CN** [comment]
已经改好，看到https://github.com/i-abc/Speedtest/issues/16#issuecomment-2044194656
下面是R2的改动，应该对中国大陆更加友好
```
# speedtest-cli，https://www.speedtest.net/zh-Hans/apps/cli
    speedtest_cli_version="1.2.0"
    speedtest_cli_tar_x86_64_sha256="5690596c54ff9bed63fa3732f818a05dbc2db19ad36ed68f21ca5f64d5cfeeb7"
    speedtest_cli_tar_i386_sha256="9ff7e18dbae7ee0e03c66108445a2fb6ceea6c86f66482e1392f55881b772fe8"
    speedtest_cli_tar_aarch64_sha256="3953d231da3783e2bf8904b6dd72767c5c6e533e163d3742fd0437affa431bd3"
    speedtest_cli_tar_armhf_sha256="e45fcdebbd8a185553535533dd032d6b10bc8c64eee4139b1147b9c09835d08d"
    speedtest_cli_tar_armel_sha256="629a455a2879224bd0dbd4b36d8c721dda540717937e4660b4d2c966029466bf"
    speedtest_cli_tar_url="https://resource.yserver.ink/speedtest/ookla-speedtest-${speedtest_cli_version}-linux-${speedtest_cli_arch}.tgz"

    # bim-core，https://github.com/veoco/bim-core
    bim_core_version="0.17.0"
    bim_core_tar_x86_64_sha256="109280fbf5a821bc56c2e83b906e65228ebc8436054b2e7861ca6db88f7e0330"
    bim_core_tar_aarch64_sha256="fa62357f94050fbb7851d1bbb7e393d8e1301281ce03c43b37dae55cbf08c198"
    bim_core_tar_url="https://resource.yserver.ink/speedtest/bimc-${bim_core_arch}-unknown-linux-musl"

    # speedtest-go，https://github.com/showwin/speedtest-go
    speedtest_go_version="1.7.7"
    speedtest_go_tar_x86_64_sha256="8345b54198a15ee066d084a15b5ab757d39f6bfc1459e31631b8a6a976bbc69a"
    speedtest_go_tar_i386_sha256="6657e8c22b788e0a75c374f41d2521218eadc24d6ec4c9d43eff5e588243eb7d"
    speedtest_go_tar_arm64_sha256="11db73962ea6113af78aea5912ffa7b561c6a2dbb97bb24734f379b6118cd888"
    speedtest_go_tar_armv7_sha256="849dcee4b130804e31c44eb1d336a9b09b9bc3a1be0793d11e964ce4dd436cba"
    speedtest_go_tar_armv6_sha256="30702860b3e012a1efb66ec72f17ed26323c97b36fdc495b48fd24002c95dc8f"
    speedtest_go_tar_url="https://resource.yserver.ink/speedtest/speedtest-go_${speedtest_go_version}_Linux_${speedtest_go_arch}.tar.gz"

    # librespeed-cli，https://github.com/librespeed/speedtest-cli
    librespeed_cli_version="1.0.10"
    librespeed_cli_tar_amd64_sha256="8e6d020c17e11dba73f0eb8a11f7ae6e3d96cdb307faf3c0ec13aa54e0cba055"
    librespeed_cli_tar_386_sha256="0121bd4a21786d5964643b00a4193edfa15389050afe5579a290e67b706ef9eb"
    librespeed_cli_tar_arm64_sha256="0ecbb98abb39f17bde2c0efae23f8446f4596c3a824aa6dda9b71723386b03ed"
    librespeed_cli_tar_armv7_sha256="b121733b9a18aa646a16393396dd7fe59e8773420a38acb05b91652c4d6cb356"
    librespeed_cli_tar_armv6_sha256="def98bbf0e79805411bca312e9e6bcddd12cd0abf4e6584a3ae05aa20c762b64"
    librespeed_cli_tar_url="https://resource.yserver.ink/speedtest/librespeed-cli_${librespeed_cli_version}_linux_${librespeed_cli_arch}.tar.gz"
```

**Comment by i-abc** [comment]
> 已经改好，看到[#16 (comment)](https://github.com/i-abc/Speedtest/issues/16#issuecomment-2044194656) 下面是R2的改动，应该对中国大陆更加友好
> 
> ```
> # speedtest-cli，https://www.speedtest.net/zh-Hans/apps/cli
>     speedtest_cli_version="1.2.0"
>     speedtest_cli_tar_x86_64_sha256="5690596c54ff9bed63fa3732f818a05dbc2db19ad36ed68f21ca5f64d5cfeeb7"
>     speedtest_cli_tar_i386_sha256="9ff7e18dbae7ee0e03c66108445a2fb6ceea6c86f66482e1392f55881b772fe8"
>     speedtest_cli_tar_aarch64_sha256="3953d231da3783e2bf8904b6dd72767c5c6e533e163d3742fd0437affa431bd3"
>     speedtest_cli_tar_armhf_sha256="e45fcdebbd8a185553535533dd032d6b10bc8c64eee4139b1147b9c09835d08d"
>     speedtest_cli_tar_armel_sha256="629a455a2879224bd0dbd4b36d8c721dda540717937e4660b4d2c966029466bf"
>     speedtest_cli_tar_url="https://resource.yserver.ink/speedtest/ookla-speedtest-${speedtest_cli_version}-linux-${speedtest_cli_arch}.tgz"
> 
>     # bim-core，https://github.com/veoco/bim-core
>     bim_core_version="0.17.0"
>     bim_core_tar_x86_64_sha256="109280fbf5a821bc56c2e83b906e65228ebc8436054b2e7861ca6db88f7e0330"
>     bim_core_tar_aarch64_sha256="fa62357f94050fbb7851d1bbb7e393d8e1301281ce03c43b37dae55cbf08c198"
>     bim_core_tar_url="https://resource.yserver.ink/speedtest/bimc-${bim_core_arch}-unknown-linux-musl"
> 
>     # speedtest-go，https://github.com/showwin/speedtest-go
>     speedtest_go_version="1.7.7"
>     speedtest_go_tar_x86_64_sha256="8345b54198a15ee066d084a15b5ab757d39f6bfc1459e31631b8a6a976bbc69a"
>     speedtest_go_tar_i386_sha256="6657e8c22b788e0a75c374f41d2521218eadc24d6ec4c9d43eff5e588243eb7d"
>     speedtest_go_tar_arm64_sha256="11db73962ea6113af78aea5912ffa7b561c6a2dbb97bb24734f379b6118cd888"
>     speedtest_go_tar_armv7_sha256="849dcee4b130804e31c44eb1d336a9b09b9bc3a1be0793d11e964ce4dd436cba"
>     speedtest_go_tar_armv6_sha256="30702860b3e012a1efb66ec72f17ed26323c97b36fdc495b48fd24002c95dc8f"
>     speedtest_go_tar_url="https://resource.yserver.ink/speedtest/speedtest-go_${speedtest_go_version}_Linux_${speedtest_go_arch}.tar.gz"
> 
>     # librespeed-cli，https://github.com/librespeed/speedtest-cli
>     librespeed_cli_version="1.0.10"
>     librespeed_cli_tar_amd64_sha256="8e6d020c17e11dba73f0eb8a11f7ae6e3d96cdb307faf3c0ec13aa54e0cba055"
>     librespeed_cli_tar_386_sha256="0121bd4a21786d5964643b00a4193edfa15389050afe5579a290e67b706ef9eb"
>     librespeed_cli_tar_arm64_sha256="0ecbb98abb39f17bde2c0efae23f8446f4596c3a824aa6dda9b71723386b03ed"
>     librespeed_cli_tar_armv7_sha256="b121733b9a18aa646a16393396dd7fe59e8773420a38acb05b91652c4d6cb356"
>     librespeed_cli_tar_armv6_sha256="def98bbf0e79805411bca312e9e6bcddd12cd0abf4e6584a3ae05aa20c762b64"
>     librespeed_cli_tar_url="https://resource.yserver.ink/speedtest/librespeed-cli_${librespeed_cli_version}_linux_${librespeed_cli_arch}.tar.gz"
> ```

这个挺好的。
