### ISSUE TITLE
debian11系统无法使用

### ISSUE THREAD

**Issue by meipian1** [i-abc/Speedtest#6]
报错如下：

![image](https://github.com/i-abc/Speedtest/assets/112554497/e994a766-44c7-4db6-8f95-6e9df8bc685a)

**Comment by i-abc** [comment]
你输入 `ps $$; echo ===; cat /etc/shells` 后回车，贴一下输出结果

**Comment by meipian1** [comment]
输出结果如下：
![image](https://github.com/i-abc/Speedtest/assets/112554497/58d0f2b4-885b-4fa1-82e7-a265a22719ad)

**Comment by i-abc** [comment]
你截第一张图的时候左边还有内容吗？

![image](https://github.com/i-abc/Speedtest/assets/104631897/3a82fd55-ea02-49c3-8496-d9f0d89a760c)

现在试试可以报错不：

```
bash <(curl -sL bash.icu/speedtest)
```

**Comment by meipian1** [comment]
你说的是这个是吧
![image](https://github.com/i-abc/Speedtest/assets/112554497/be4652fa-78fc-492f-81fd-7c226b5c315c)
我好像发现问题了，如果我用screen开了一个会话窗口，在会话窗口里面，那么前面就是只有#，在这种情况下是无法执行的，
然后ps $$; echo ===; cat /etc/shells的命令如上图所示

如果我不开screen，直接执行，是可以运行你的脚本的。

**Comment by i-abc** [comment]
> 你说的是这个是吧 ![image](https://user-images.githubusercontent.com/112554497/268207815-be4652fa-78fc-492f-81fd-7c226b5c315c.png) 我好像发现问题了，如果我用screen开了一个会话窗口，在会话窗口里面，那么前面就是只有#，在这种情况下是无法执行的， 然后ps $$; echo ===; cat /etc/shells的命令如上图所示
> 
> 如果我不开screen，直接执行，是可以运行你的脚本的。

那你可以这样解决：在开 screen 后，先敲一个 `bash` 回车（行首部分会变回没开 screen 时的样子），然后再执行 `bash <(curl -sL bash.icu/speedtest)`，应该就没问题了

**Comment by meipian1** [comment]
试了一下，确实可以了，大佬厉害了
![image](https://github.com/i-abc/Speedtest/assets/112554497/5e0765b1-88d4-47ee-b39b-acf0b60fe688)
