### ISSUE TITLE
测速占空间

### ISSUE THREAD

**Issue by jorejia** [i-abc/Speedtest#7]
测速下载的临时文件存放在哪里呢，为何会占用空间

**Comment by i-abc** [comment]
> 测速下载的临时文件存放在哪里呢，为何会占用空间

脚本执行时所在路径下的 `./sp-github-i-abc`，测试跑完会自动删。

你空间少了多少？

**Comment by jorejia** [comment]
是我的原因，复查了一下，后台有其他下载，测速占用空间很小，结束正常删除临时文件，没有问题
